# Generated by Django 5.2.10 on 2026-01-31 04:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("CUSTOMER", "Customer"),
                    ("MANAGER", "Restaurant Manager"),
                    ("OWNER", "Restaurant Owner"),
                    ("STAFF", "Staff"),
                    ("WAITER", "Waiter"),
                    ("CASHIER", "Cashier"),
                ],
                default="CUSTOMER",
                max_length=20,
            ),
        ),
    ]
