# Generated by Django 5.2.10 on 2026-02-18 02:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_promophonenumber"),
        ("profiles", "0003_alter_customuser_role"),
    ]

    operations = []
