# Generated by Django 5.2.10 on 2026-02-19 03:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("menu", "0006_restaurant_view_menu_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Amount",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", max_length=3, verbose_name="Currency"
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Monthly"),
                            ("YEARLY", "Yearly"),
                            ("BI_YEARLY", "Bi-Yearly"),
                        ],
                        max_length=10,
                        verbose_name="Billing Cycle",
                    ),
                ),
                ("period_start", models.DateTimeField(verbose_name="Period Start")),
                ("period_end", models.DateTimeField(verbose_name="Period End")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("FAILED", "Failed"),
                            ("REFUNDED", "Refunded"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("STRIPE", "Stripe"),
                            ("PAYPAL", "PayPal"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("CASH", "Cash"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Payment Method",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="External payment system transaction ID",
                        max_length=100,
                        verbose_name="Transaction ID",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Paid At"),
                ),
                (
                    "failed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Failed At"
                    ),
                ),
                (
                    "failure_reason",
                    models.TextField(blank=True, verbose_name="Failure Reason"),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Discount Amount",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Tax Amount",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Total Amount",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Billing Record",
                "verbose_name_plural": "Billing Records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("BASIC", "Basic"),
                            ("GOLD", "Gold"),
                            ("PLATINUM", "Platinum"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="Plan Name",
                    ),
                ),
                (
                    "monthly_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price for monthly billing cycle",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Monthly Price",
                    ),
                ),
                (
                    "yearly_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price for yearly billing cycle (12 months)",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Yearly Price",
                    ),
                ),
                (
                    "bi_yearly_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price for bi-yearly billing cycle (24 months)",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Bi-Yearly Price",
                    ),
                ),
                (
                    "max_menu_items",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="Maximum number of menu items allowed",
                        verbose_name="Max Menu Items",
                    ),
                ),
                (
                    "max_categories",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Maximum number of categories allowed",
                        verbose_name="Max Categories",
                    ),
                ),
                (
                    "max_menu_groups",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Maximum number of menu groups allowed",
                        verbose_name="Max Menu Groups",
                    ),
                ),
                (
                    "max_staff_users",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="Maximum number of staff users allowed",
                        verbose_name="Max Staff Users",
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        default=dict,
                        help_text="JSON object containing plan features",
                        verbose_name="Features",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Subscription Plan",
                "verbose_name_plural": "Subscription Plans",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BillingInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Invoice Number"
                    ),
                ),
                ("invoice_date", models.DateField(verbose_name="Invoice Date")),
                ("due_date", models.DateField(verbose_name="Due Date")),
                ("billing_address", models.TextField(verbose_name="Billing Address")),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "terms_and_conditions",
                    models.TextField(blank=True, verbose_name="Terms and Conditions"),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="invoices/",
                        verbose_name="PDF File",
                    ),
                ),
                ("is_sent", models.BooleanField(default=False, verbose_name="Is Sent")),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Sent At"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "billing_record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice",
                        to="billing.billingrecord",
                        verbose_name="Billing Record",
                    ),
                ),
            ],
            options={
                "verbose_name": "Billing Invoice",
                "verbose_name_plural": "Billing Invoices",
                "ordering": ["-invoice_date"],
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("STRIPE", "Stripe"),
                            ("PAYPAL", "PayPal"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("CASH", "Cash"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Method Type",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Is Default"),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Stripe Customer ID"
                    ),
                ),
                (
                    "stripe_payment_method_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Stripe Payment Method ID",
                    ),
                ),
                (
                    "card_last_four",
                    models.CharField(
                        blank=True, max_length=4, verbose_name="Card Last Four"
                    ),
                ),
                (
                    "card_brand",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Card Brand"
                    ),
                ),
                (
                    "card_expiry_month",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Card Expiry Month"
                    ),
                ),
                (
                    "card_expiry_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Card Expiry Year"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to="menu.restaurant",
                        verbose_name="Restaurant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Method",
                "verbose_name_plural": "Payment Methods",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RestaurantSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Monthly"),
                            ("YEARLY", "Yearly"),
                            ("BI_YEARLY", "Bi-Yearly"),
                        ],
                        default="MONTHLY",
                        max_length=10,
                        verbose_name="Billing Cycle",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                            ("SUSPENDED", "Suspended"),
                            ("TRIAL", "Trial"),
                        ],
                        default="TRIAL",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "trial_end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Trial End Date"
                    ),
                ),
                (
                    "current_period_start",
                    models.DateTimeField(verbose_name="Current Period Start"),
                ),
                (
                    "current_period_end",
                    models.DateTimeField(verbose_name="Current Period End"),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Cancelled At"
                    ),
                ),
                (
                    "price_at_subscription",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Price at Subscription",
                    ),
                ),
                (
                    "auto_renew",
                    models.BooleanField(default=True, verbose_name="Auto Renew"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "restaurant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="menu.restaurant",
                        verbose_name="Restaurant",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="billing.subscriptionplan",
                        verbose_name="Subscription Plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Restaurant Subscription",
                "verbose_name_plural": "Restaurant Subscriptions",
            },
        ),
        migrations.AddField(
            model_name="billingrecord",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="billing_records",
                to="billing.restaurantsubscription",
                verbose_name="Subscription",
            ),
        ),
    ]
