# Generated by Django 5.2.10 on 2026-02-19 03:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplan",
            name="features",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON object containing plan features",
                null=True,
                verbose_name="Features",
            ),
        ),
    ]
