# Generated by Django 5.2.10 on 2026-02-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0002_alter_subscriptionplan_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurantsubscription",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Fixed discount amount (overrides percentage if set)",
                max_digits=10,
                verbose_name="Discount Amount",
            ),
        ),
        migrations.AddField(
            model_name="restaurantsubscription",
            name="discount_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Discount percentage (e.g., 25.00 for 25% discount)",
                max_digits=5,
                verbose_name="Discount Percentage",
            ),
        ),
        migrations.AddField(
            model_name="restaurantsubscription",
            name="final_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Final price after discount",
                max_digits=10,
                verbose_name="Final Price",
            ),
            preserve_default=False,
        ),
    ]
