# Generated by Django for one-time billing support
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_restaurantsubscription_discount_amount_and_more'),
    ]

    operations = [
        # Add new billing cycle choices to BillingRecord
        migrations.AlterField(
            model_name='billingrecord',
            name='billing_cycle',
            field=models.CharField(
                choices=[
                    ('MONTHLY', 'Monthly'),
                    ('YEARLY', 'Yearly'),
                    ('BI_YEARLY', 'Bi-Yearly'),
                    ('ONE_TIME', 'One-Time'),
                ],
                max_length=10,
                verbose_name='Billing Cycle'
            ),
        ),
        
        # Add description field to BillingRecord
        migrations.AddField(
            model_name='billingrecord',
            name='description',
            field=models.CharField(
                blank=True,
                max_length=200,
                verbose_name='Description',
                help_text='Description of the billing item (e.g., "Setup Fee", "Custom Feature")'
            ),
        ),
        
        # Make period_start optional
        migrations.AlterField(
            model_name='billingrecord',
            name='period_start',
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name='Period Start',
                help_text='Required for recurring payments, optional for one-time payments'
            ),
        ),
        
        # Make period_end optional
        migrations.AlterField(
            model_name='billingrecord',
            name='period_end',
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name='Period End',
                help_text='Required for recurring payments, optional for one-time payments'
            ),
        ),
    ]
