# Generated by Django 5.2.10 on 2026-01-24 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0002_alter_restaurant_options_menuitem_allergens_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('RESTAURANT_MANAGER', 'Restaurant Manager'), ('KITCHEN_STAFF', 'Kitchen Staff')], default='KITCHEN_STAFF', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(blank=True, help_text='Restaurant this user belongs to (null for super admins)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='menu.restaurant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Restaurant User',
                'verbose_name_plural': 'Restaurant Users',
                'db_table': 'restaurant_users',
                'indexes': [models.Index(fields=['user'], name='restaurant__user_id_631792_idx'), models.Index(fields=['restaurant'], name='restaurant__restaur_f64612_idx')],
            },
        ),
    ]
