# Generated by Django 5.2.10 on 2026-01-25 05:58

import cloudinary_storage.storage
import django.db.models.deletion
import menu.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MenuGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=100)),
                ("group_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["group_order"],
            },
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("phone", models.CharField(blank=True, max_length=50)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                        upload_to=menu.models.restaurant_logo_path,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MenuCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                        upload_to=menu.models.menu_category_path,
                    ),
                ),
                ("cat_order", models.PositiveIntegerField(default=0)),
                (
                    "menu_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="menu.menugroup",
                    ),
                ),
            ],
            options={
                "ordering": ["cat_order"],
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                        upload_to=menu.models.menu_item_path,
                    ),
                ),
                ("item_order", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="menu.menucategory",
                    ),
                ),
            ],
            options={
                "ordering": ["item_order"],
            },
        ),
        migrations.AddField(
            model_name="menugroup",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu_groups",
                to="menu.restaurant",
            ),
        ),
    ]
