# Generated by Django 5.2.10 on 2026-01-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="facebook_url",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="instagram_url",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="tiktok_url",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
