# Generated by Django 5.2.10 on 2026-01-26 01:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0002_restaurant_facebook_url_restaurant_instagram_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="is_disabled",
            field=models.BooleanField(default=False),
        ),
    ]
