# Generated by Django 5.2.10 on 2026-01-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0003_menuitem_is_disabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="is_highlight",
            field=models.BooleanField(default=False),
        ),
    ]
