# Generated by Django 5.2.10 on 2026-01-31 02:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0004_menuitem_is_highlight"),
    ]

    operations = [
        migrations.AddField(
            model_name="menucategory",
            name="is_disabled",
            field=models.BooleanField(default=False),
        ),
    ]
