# Generated by Django 5.2.10 on 2026-01-31 04:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0005_menucategory_is_disabled"),
        ("order", "0002_alter_order_table"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="nepali_date",
            field=models.CharField(
                blank=True,
                help_text="Nepali date in YYYY-MM-DD format",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="nepali_day",
            field=models.PositiveIntegerField(
                blank=True, help_text="Nepali day (1-32)", null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="nepali_month",
            field=models.PositiveIntegerField(
                blank=True, help_text="Nepali month (1-12)", null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="nepali_year",
            field=models.PositiveIntegerField(
                blank=True, help_text="Nepali year (e.g., 2081)", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["nepali_date"], name="order_order_nepali__51f9af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["nepali_year", "nepali_month"],
                name="order_order_nepali__0ccdb9_idx",
            ),
        ),
    ]
