# Generated by Django 5.2.10 on 2026-01-31 05:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0003_order_nepali_date_order_nepali_day_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("preparing", "preparing"),
                    ("ready", "ready"),
                    ("served", "served"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("in_progress", "in_progress"), ("completed", "completed")],
                default="in_progress",
                max_length=20,
            ),
        ),
    ]
