# Generated by Django 5.2.10 on 2026-01-31 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0004_orderitem_created_at_orderitem_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="final_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Final amount with VAT",
                max_digits=12,
                null=True,
            ),
        ),
    ]
